
export const metadata = {
  title: 'About Meta Data',
  description: 'Generated by About Page',
}
const About = () => {
  return (
    <div>
      <h1>About me</h1>
    </div>
  )
}

export default About
